version: '3.7'

services:
  web:
    build: ./chat_websockets/
    command: ./run_env.sh
    volumes:
    - type: bind
      source: ~/hendrix_logs01/
      target: /home/app/web/logs/run/
    ports:
      - 8000:8080
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=chatw
      - POSTGRES_PASSWORD=chatw
      - POSTGRES_DB=chatw

  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
