version: '3.7'

services:
  web:
    build: ./chat_websockets/
    #command: sleep 1000
    command: ./run_env.sh
    volumes:
    - type: bind
      source: ~/hendrix_logs01/
      target: /home/app/web/logs/run/
    ports:
      - 8000:8080
    #extra_hosts:
    #  - "database:172.17.0.1"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=chatw
      - POSTGRES_PASSWORD=chatw
      - POSTGRES_DB=chatw

  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
# docker-compose exec web python manage.py migrate --noinput
# docker-compose exec db psql --username=chatw --dbname=chatw
